export const data = {
    categories: [
      { en: "backgrounds", vi: "Hình nền" },
      { en: "fashion", vi: "Thời trang" },
      { en: "nature", vi: "Thiên nhiên" },
      { en: "science", vi: "Khoa học" },
      { en: "education", vi: "Giáo dục" },
      { en: "feelings", vi: "Cảm xúc" },
      { en: "health", vi: "Sức khỏe" },
      { en: "people", vi: "Con người" },
      { en: "religion", vi: "Tôn giáo" },
      { en: "places", vi: "Địa điểm" },
      { en: "animals", vi: "Động vật" },
      { en: "industry", vi: "Công nghiệp" },
      { en: "computer", vi: "Máy tính" },
      { en: "food", vi: "Thức ăn" },
      { en: "sports", vi: "Thể thao" },
      { en: "transportation", vi: "Giao thông" },
      { en: "travel", vi: "Du lịch" },
      { en: "buildings", vi: "Tòa nhà" },
      { en: "business", vi: "Kinh doanh" },
      { en: "music", vi: "Âm nhạc" },
    ],
    filters: {
      order: [
        { en: "popular", vi: "Phổ biến" },
        { en: "latest", vi: "Mới nhất" },
      ],
      orientation: [
        { en: "all", vi: "Tất cả" },
        { en: "horizontal", vi: "Ngang" },
        { en: "vertical", vi: "Dọc" },
      ],
      type: [
        { en: "all", vi: "Tất cả" },
        { en: "photo", vi: "Ảnh" },
        { en: "illustration", vi: "Minh họa" },
        { en: "vector", vi: "Vector" },
      ],
      colors: [
        { en: "red", vi: "Đỏ" },
        { en: "orange", vi: "Cam" },
        { en: "yellow", vi: "Vàng" },
        { en: "green", vi: "Xanh lá" },
        { en: "turquoise", vi: "Xanh ngọc" },
        { en: "blue", vi: "Xanh dương" },
        { en: "pink", vi: "Hồng" },
        { en: "white", vi: "Trắng" },
        { en: "gray", vi: "Xám" },
        { en: "black", vi: "Đen" },
        { en: "brown", vi: "Nâu" },
      ],
    },
  };
  